"""manual revision test

Revision ID: e061c796af18
Revises: 
Create Date: 2025-05-17 20:55:46.761059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e061c796af18"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_id", table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.NUMERIC(), nullable=False),
        sa.Column("content", sa.VARCHAR(), nullable=False),
        sa.Column("sentiment", sa.VARCHAR(), nullable=False),
        sa.Column("score", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_id", "messages", ["id"], unique=False)
    # ### end Alembic commands ###
