name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python install
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Poetry install
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 2.1.1

      - name: Deps install
        run: poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Run test coverage
        run: poetry run pytest --cov=app --cov-report=term-missing
