name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Install render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/renderinc/render-cli/main/install.sh | bash
          export PATH="$HOME/.render/bin:$PATH"
          render --version

      - name: Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          PATH: ${{ env.PATH }}:/home/runner/.render/bin
        run: |
          render deploy \
            --service-id ${{ secrets.RENDER_SERVICE_ID }} \
            --branch main \
            --yes
