name: Deploy para Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar o Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential procps curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Instalar o Render CLI
        run: |
          brew install render
          render --version

      - name: Deploy para o Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm
