name: Deploy para Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential procps curl file git

      - name: Instalar Homebrew
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Adicionar Homebrew ao PATH
        run: echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc

      - name: Inicializar ambiente do Homebrew e instalar Render CLI
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install render
          render --version

      - name: Deploy para o Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm
