name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar o Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/latest/download/render-linux-amd64 -o render
          chmod +x render
          sudo mv render /usr/local/bin/render
          render --version

      - name: Deploy para o Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm
